version: '3.3'

services:
  pulsar-api:
    image: pulsar-api-dev
    build:
       context: .
       dockerfile: Dockerfile
    container_name: pulsar-api-dev
    working_dir: /app 
    ports: 
      - 3010:3010
    volumes:
      - ..:/app
    depends_on:
      - document_store
    # Make sure the dev container doesn't exit right away:
    command: sleep infinity
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - API_BASE_URI=http://localhost:3010
      - DOCUMENT_STORE_SERVER_URL=http://document_store:8080
      - DOCUMENT_STORE_NAME=AlphaCentauri
      - AUTH_AUTHORITY=https://dev-wkngfk2k.au.auth0.com/
      - AUTH_AUDIENCE=https://alpha-centauri-api@pulsar.com
      - AUTH_CLIENT_ID=pyxvaVrmLOWyDWl5eRldzHZWwdNqCVaY
      - AUTH_CLIENT_SECRET=D49YkQaAWASs1Yro0LMT04up_LMAglJiRaJL388WN3vGWeBWftckrKc4V2-_WDge
  
  document_store:
    image: ravendb/ravendb:5.1-ubuntu-latest
    container_name: pulsar-doc-store-dev
    environment: 
      - RAVEN_ARGS=--Setup.Mode=None
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
      - RAVEN_License_Eula_Accepted=true
    ports: 
      - 8080:8080


  
